WINDOW_WIDTH = 1280
WINDOW_HEIGHT = 720
CELL_SIZE = 80
FPS = 60
BUTTON_COLOR = {
    "normal" : (70, 130, 180),
    "shadow" : (40, 80, 120),
    "highlight" : (130, 190, 230)
}
MENU_COORDINATE = (800, 40)
MENU_WIDTH = 400
MENU_HEIGHT = 640
ANIMATION_TIME = 200
BOARD_COORDINATE = (80 ,40)
BLACK = (0, 0, 0)
WHITE = (255, 255, 255)
WHITE_CELL = (215, 220, 225)
BLACK_CELL = (130, 145, 160)
BACKGROUND_COLOR = (50, 50, 50)
FONT_PATH = "data/fonts/Inkfree.ttf"
BLACK_PAWN_PIECE_IMAGE_PATH = ""
BLACK_ROOK_PIECE_IMAGE_PATH = "data/images/rook_black.png"
BLACK_KNIGHT_PIECE_IMAGE_PATH = "data/images/knight_black.png"
BLACK_BISHOP_PIECE_IMAGE_PATH = "data/images/bishop_black.png"
BLACK_QUEEN_PIECE_IMAGE_PATH = "data/images/queen_black.png"
BLACK_KING_PIECE_IMAGE_PATH = "data/images/king_black.png"
WHITE_PAWN_PIECE_IMAGE_PATH = ""
WHITE_ROOK_PIECE_IMAGE_PATH = ""
WHITE_KNIGHT_PIECE_IMAGE_PATH = ""
WHITE_BISHOP_PIECE_IMAGE_PATH = ""
WHITE_QUEEN_PIECE_IMAGE_PATH = ""
WHITE_KING_PIECE_IMAGE_PATH = ""
POSSIBLE_DESTINATION_IMAGE_PATH = "data/images/point.png"

